FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    wget \
    mysql-client \
    bzip2 \
    findutils \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY update-eve-data.sh /app/update-eve-data.sh
RUN chmod +x /app/update-eve-data.sh

COPY init-db.sh /app/init-db.sh
RUN chmod +x /app/init-db.sh

CMD ["/app/update-eve-data.sh"]
